logging:
  level:
    ROOT: INFO
    com.mnp.store: INFO

spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://ecom20.mysql.database.azure.com:3306/temp?useUnicode=true&characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

server:
  port: 4000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
